// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR40cVlcYWeDeX4HuOoEDbE_cRQ3aJ9Ig',
    appId: '1:677943389995:web:1169627f02a2be74e25f6e',
    messagingSenderId: '677943389995',
    projectId: 'beyoundthecall',
    authDomain: 'beyoundthecall.firebaseapp.com',
    storageBucket: 'beyoundthecall.appspot.com',
    measurementId: 'G-65EXGQFLMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA6Bbrws9h9AFELD9LNQFCaONgy0V0kaE',
    appId: '1:677943389995:android:c8e6adebf6bb2a5be25f6e',
    messagingSenderId: '677943389995',
    projectId: 'beyoundthecall',
    storageBucket: 'beyoundthecall.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSqqwdweC2n20Msd_7sV-TeceEvAIXTWw',
    appId: '1:880129103791:ios:387faaa9788616205bc15a',
    messagingSenderId: '880129103791',
    projectId: 'lorema-d6513',
    storageBucket: 'lorema-d6513.firebasestorage.app',
    androidClientId: '880129103791-nedshv731g64r037c0vmlm55dv8opqf9.apps.googleusercontent.com',
    iosClientId: '880129103791-0g50ciudj15pjhs4c9vdbk2l7600id00.apps.googleusercontent.com',
    iosBundleId: 'com.example.brightmindsAdmin',
  );
}